
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIV LP MINUS MUL NUMBER PLUS RPexp : exp PLUS facexp : exp MINUS facexp : facfac : fac MUL termfac : fac DIV termfac : termterm : LP exp RPterm : NUMBER'
    
_lr_action_items = {'LP':([0,4,6,7,8,9,],[4,4,4,4,4,4,]),'NUMBER':([0,4,6,7,8,9,],[5,5,5,5,5,5,]),'$end':([1,2,3,5,11,12,13,14,15,],[0,-3,-6,-8,-1,-2,-4,-5,-7,]),'PLUS':([1,2,3,5,10,11,12,13,14,15,],[6,-3,-6,-8,6,-1,-2,-4,-5,-7,]),'MINUS':([1,2,3,5,10,11,12,13,14,15,],[7,-3,-6,-8,7,-1,-2,-4,-5,-7,]),'RP':([2,3,5,10,11,12,13,14,15,],[-3,-6,-8,15,-1,-2,-4,-5,-7,]),'MUL':([2,3,5,11,12,13,14,15,],[8,-6,-8,8,8,-4,-5,-7,]),'DIV':([2,3,5,11,12,13,14,15,],[9,-6,-8,9,9,-4,-5,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'exp':([0,4,],[1,10,]),'fac':([0,4,6,7,],[2,2,11,12,]),'term':([0,4,6,7,8,9,],[3,3,3,3,13,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> exp PLUS fac','exp',3,'p_expression_sum','main.py',9),
  ('exp -> exp MINUS fac','exp',3,'p_expression_minus','main.py',13),
  ('exp -> fac','exp',1,'p_expression','main.py',17),
  ('fac -> fac MUL term','fac',3,'p_factor_mul','main.py',21),
  ('fac -> fac DIV term','fac',3,'p_factor_div','main.py',25),
  ('fac -> term','fac',1,'p_factor','main.py',29),
  ('term -> LP exp RP','term',3,'p_term_paren','main.py',33),
  ('term -> NUMBER','term',1,'p_term_num','main.py',37),
]
